# Generated by Django 3.1.3 on 2020-11-29 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201129_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='id_published',
            new_name='is_published',
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.category', verbose_name='Категорія'),
        ),
    ]
